gene/tales-of-privacy-1
josipkoncurat/blog pull request #10
Opened 2021-04-23 14:01 UTC by ajingene

raw text version

2021-04-23 19:01 UTC, josipkoncurat requested changes
The post is nicely put, It gave some nice insight on privacy in Bitcoin and how it was achieved in Monero. Do you think governments will ever allow private blockchains to be used freely? 
The current system is far away from real privacy, this would be a big shift.

Check out my comments but anyway well done!

2021-04-24 21:52 UTC, ajingene commented on _posts/2021-04-23-gene-tales-of-privacy-1.html
> +   you if that other party reveals your data.
KYC in general. For example if you're buying products over the Internet, (like on a webshop that supports bitcoin). Maybe in some cases it's enough to just leave an email address, but in most cases you'd have to write your name and street address.

2021-04-24 21:56 UTC, ajingene commented on _posts/2021-04-23-gene-tales-of-privacy-1.html
> +actually private in many a use case.  Because, as stated at the start
It means the same thing as what you wrote, it's just in a different style. I would say "many a use case" is more elegant and poetic. I put it there "teasingly", to loosen the atmosphere. Becasuse an elegant phrase is unexpected for this subject.

2021-04-24 21:56 UTC, ajingene commented on _posts/2021-04-23-gene-tales-of-privacy-1.html
> +written down anywhere in it.  However, that doesn't make bitcoin
ok

2021-04-24 21:57 UTC, ajingene commented on _posts/2021-04-23-gene-tales-of-privacy-1.html
> +transaction history (criminal in the literal sense).  The freshly
Yeah, I'll edit it in the non-raw-text version to look better.

2021-04-24 21:58 UTC, ajingene commented on _posts/2021-04-23-gene-tales-of-privacy-1.html
> +course!  You buy it in cash, don't leak your details ever, and trade
It's the same as saying "It's simple, of course!"
In general, "why of course" == "of course".  Again, it sounds a bit more elegant. Like a fat middle aged British man is saying it with a smile.

2021-04-25 07:56 UTC, ajingene commented
>Do you think governments will ever allow private blockchains to be used freely?
As long as they can hack the system (break it, get around the privacy), most governments probably won't ban it. But the question is also how to ban it effectively and can it really be done.

2021-04-25 09:13 UTC, ajingene commented
did some changes

2021-04-25 13:39 UTC, merged